### ISSUE TITLE
Empty campaigns when including attribute `campaign.labels` in report

### ISSUE THREAD

**Issue by mledwards** [Opteo/google-ads-api#106]
### I'm submitting a bug report.

Hi there,

I can retrieve a campaigns report from the API fine, but when I also try and get `campaign.labels` I get an empty campaigns array, with the error `Internal error encountered`.

Could be related to https://github.com/Opteo/google-ads-api/pull/53#issue-282056333?

Here are the options I'm sending to the report:

```
Campaigns = await Account.report({
      entity: "campaign",
      attributes: ["campaign.id", "campaign.name", "campaign.status", "campaign.labels"],
      metrics: ["metrics.clicks", "metrics.impressions", "metrics.conversions", "metrics.cost_micros"],
      constraints: [
        { key: "metrics.impressions", op: ">", val: 0 } // Get for current campaign
      ],
      date_constant: "LAST_30_DAYS",
      order_by: "campaign.name",
      segments: ["segments.date"]
    });
```

Without `campaign.labels` it works just fine.

**Comment by kritzware** [comment]
Hi @mledwards, unfortunately the error `Internal error encountered` means the issue is coming from Google's end. 

We did contact them about problems with selecting `campaign.labels` before, and they told us it was a known issue in the beta. I haven't tried since then, but your query does seem perfectly fine.

I'm afraid there isn't much we can do here, except wait for Google to fix the issue. I'd also suggest you raise the problem with them [over on their forums](https://groups.google.com/forum/#!forum/adwords-api).

**Comment by mledwards** [comment]
Thanks @kritzware. I've dug a little deeper, and it looks like labels can only be retrieved if they're done without segmentation. This sort of makes sense as the labels are consistent across the campaign, so we only need to get them once.

It does make my logic a little more complex, as I now have to do another report just to get the labels and then map them into the segmented report, but that's not too much extra work.

**Comment by kritzware** [comment]
Alright, glad to hear you sorted it out! 👍
