### ISSUE TITLE
How to obtaion the quota usage

### ISSUE THREAD

**Issue by Zikoel** [Opteo/google-ads-api#128]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [X] question about how to use this project

### Summary
I'm trying to understand how to retrieve quota usage from Google APIs or from this library. Unfortunately I can't find nothing inside the lib docs and worse nothing from the Google documentation. Any idea on how to get this info ?

### Other information
I notice that the lib use `bottleneck` maybe this is information exist..

**Comment by kritzware** [comment]
I don't believe you can query the API for your quota usage, but the official documentation has a detailed page regarding API limits & quotas: https://developers.google.com/google-ads/api/docs/best-practices/quotas

**Comment by Zikoel** [comment]
Obviously I have read the page that you suggest! But but to know what are the limits doesn't close the question! There is a counter or something like that inside the google-ads-api Opteo library or I should count my request on my code ? Why you internally use bottleneck if you don't have this value ?

**Comment by avermeil** [comment]
There is no counter inside of the library -- it was designed with Standard Access tokens in mind. We use Bottleneck to throttle requests to roughly 100/second in order to avoid hitting Google's rate limits.

There is certainly scope to add come kind of counter to this library to help with Basic Access quotas, although I'm not sure how we could persist this daily counter through process restarts. PRs welcome!
