### ISSUE TITLE
Discovery campaigns cannot be fetched

### ISSUE THREAD

**Issue by grinsteindavid** [Opteo/google-ads-api#146]
### I'm submitting a ...

-   [x] bug report
-   [x] feature request

### Summary

When using:

`let result = await customer.campaigns.list()`

It fetches all the remote campaigns but not the campaigns of discovery type https://support.google.com/google-ads/answer/9176876?hl=en

**Comment by avermeil** [comment]
Hi @grinsteindavid ,

The Google Ads API doesn't support discovery campaigns yet, that's why they aren't showing up. Google hasn't given us an ETA on when they will add support. You might have better luck using the old adwords api (https://developers.google.com/adwords/api/docs/guides/start), but I'm not certain that they are there either.
