### ISSUE TITLE
CPU usage goes 100% with v6

### ISSUE THREAD

**Issue by doguh** [Opteo/google-ads-api#211]
### I'm submitting a ...

-   [X] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

Hey there, I'm trying to upgrade to Google Ads API v6, because I was using v3 and it is down for a couple weeks now.

I'm using `google-ads-api@4.0.4-beta.11`, so I'm not sure if this an issue with stable v4, but it was definitely not an issue with v3.

The issue I have is that `customer.query` blocks the main threads and causes 100% CPU usage.

Example:
```js
const client= new GoogleAdsApi({
  client_id,
  client_secret,
  developer_token,
});

const customer = client.Customer({
  customer_id,
  login_customer_id,
  refresh_token,
});

// list customers under the main account
const result = await customer.query('SELECT customer_client.descriptive_name, customer_client.id FROM customer_client');

// list campaigns for a given customer
const campaigns = await customer.report({
  entity: 'campaign',
  attributes: [
    'campaign.id',
    'campaign.name',
    'campaign.app_campaign_setting.app_id',
    'campaign.app_campaign_setting.app_store',
  ],
  metrics: ['metrics.impressions'],
  from_date,
  to_date,
});
```

In the example above, calls to `customer.query` or `customer.report` will cause the thread to be blocked.

This can be pointed out easily by simply printing something every few ms:
```js
// add this before the first line
setInterval(() => console.log(1), 16);
```

This is a real problem when this module is used in a service that takes for example HTTP requests. Also in production environment, the health check would fail because the service would not respond in time due to the thread being locked (+ the fact that CPU usage is at 100% for no apparent reason).

### Other information

I know this is a beta version, but I wanted to share this to make sure you are aware of it!

Anyway thanks for the awesome module, it makes working with Google Ads API wayyyyy lot easier.

**Comment by kritzware** [comment]
Hi @doguh, thanks for making this issue. This is really useful information to know.

We'll make sure to investigate this further, but I have a suspicion this will be due to the sheer amount of protos imported in the main `GoogleAdsService`. This service imports all other Google Ads API services inside it, however this is done within code generated by [Gapic](https://github.com/googleapis/gapic-generator), so we may not be able to do much about this. 

I'm also aware that the official client libraries have similar problems with CPU usage due to the amount of protos in the Google Ads API.

> Anyway thanks for the awesome module, it makes working with Google Ads API wayyyyy lot easier.

Thanks for this comment as well! 🎉
