### ISSUE TITLE
Get a OOM error when download big reports

### ISSUE THREAD

**Issue by lushu** [Opteo/google-ads-api#229]
Hi,

We found a performance issue here. When download big reports, e.g. over 500MB in a Cloud Functions env (2G memory maximum), the 'google-ads-api' library will generate an OOM error. (However, the previous 'google-ads-node' can download the report smoothly to Cloud Storage. I didn't have the chance to test the new version yet.)

After I checked the code, I think may these two [arrays](https://github.com/Opteo/google-ads-api/blob/053ecf6a22f7da56b3ee7950445929858ca00c0d/src/customer.ts#L133) are the reason caused OOM. Can you have a look of this issue? Thank you.

**Comment by WillCooter** [comment]
Yes you're right. In the `reportStream` method the aim of the accumulator was to collate the results of the search stream so that they could be accessed as a single array in the post query hook. However this does somewhat defeat the purpose of streaming, so I will remove that accumulator and disallow access to the response in the post query hook for report streaming.

However, the regular `report` and `query` methods which internally use pagination will continue to collate the pages into one response, and hence provide access to the entire response in the post query hook (important for cacheing the results). Therefore it is advisable not to use the `report` method for big reports and instead use `reportStream` (once I have removed the accumulator), or to use [google-ads-node](https://github.com/Opteo/google-ads-node) and handle the pagination manually.

**Comment by WillCooter** [comment]
The accumulator has been removed in `v5.1.0`, so hopefully this issue should be behind us. If anything else comes up then let us know, and thankyou for bringing up the issue in the first place 🙂

**Comment by lushu** [comment]
Thanks for the quick fix. However, I have other thoughts regarding the performance:

- The function is named as 'reportStream' while it returns a 'generator'.
- In some (if not most) cases, we use 'reportStream' to pipe it to a writeStream instead of handling the data in the position where we get the reports. Google Ads reports are offered based on single Ads account and the most common use case is to handle all Ads accounts reports from a same MCC account at the same time. So we need to download those reports first.
- Transforming stream to generator and later generator back to streams seems to be a waste. 
- Can we offer two different functions at 'google-ads-api' level, e.g. 'reportGeneratorOnStream' which returns current generator and 'reportStream' to return the original stream?

Thank you.
