### ISSUE TITLE
API Calls are too slow

### ISSUE THREAD

**Issue by flasaracina** [Opteo/google-ads-api#230]
Hello,
I recently upgraded `google-ads-api` to version `5.0.3` hoping to overcome all the problems I had with version `4.0.3`. The GRPC library used by `google-ads-api` in version `4.0.3` randomly returned some obscure `Stream Removed` error, so as soon as I read that the newer version is using a different GRPC library I was keen on upgrading my codebase to the latest version.

Alas, it turned out that this code:

```js
const customer = new Customer(
    clientOptions,
    {
        customer_id: id || process.env.GOOGLE_ADS_CUSTOMER_ID,
        login_customer_id: process.env.GOOGLE_ADS_CUSTOMER_ID,
        refresh_token: process.env.GOOGLE_ADS_REFRESH_TOKEN
    }, 
    {
        onQueryStart({ credentials, query, reportOptions, cancel, editOptions }) {
            console.log("q", query)
        },
        onQueryError({ credentials, query, reportOptions, error }) {
            console.log("err", error);
        }
    }
)

let data = await customer.query('SELECT customer_client.descriptive_name, customer_client.id FROM customer_client')
```

took about 42 seconds to resolve.

Am I missing something? Why is it so slow?

Thanks

**Comment by kritzware** [comment]
Hi @flasaracina, thanks for making this issue.

I've just ran your code and am not able to make it run that slowly. I get speeds of around 7-8 seconds.

Because of the new Gapic generated code we're using, the **first** call will always be several seconds as it does some initial authentication and loads in lots of proto files into the main `GoogleAdsService`. 

However, 42 seconds does seem very slow. How large is the Google Ads account you're running that code for? How many customer rows are returned in `data`?

**Comment by flasaracina** [comment]
Hi @kritzware 
The Google account will return 500+ rows. I know this seems quite alot but with version `4.0.3` the same query with the exact same result set run much more faster ( a couple of seconds in the worst case).

I also want to point out that if I run some calls in parallel, let's say like this:

```js

// mind that the code shown here is just a barebone example...

const getCustomer = (id) => {
	return new Customer(
		clientOptions,
		{
			customer_id: id || process.env.GOOGLE_ADS_CUSTOMER_ID,
			login_customer_id: process.env.GOOGLE_ADS_CUSTOMER_ID,
			refresh_token: process.env.GOOGLE_ADS_REFRESH_TOKEN
		}, {
		onQueryStart({ credentials, query, reportOptions, cancel, editOptions }) {
			console.log("q", query)
		},
		onQueryError({ credentials, query, reportOptions, error }) {
			console.log("err", error);
		}
	}
	)
}

const getInfo = async id => {
	let customer = await getCustomer(id);
	return await customer.query('SELECT customer_client.descriptive_name, customer_client.id FROM customer_client')
}

let adsusers = [...]; // 23 google ads account ids
let results = await Promise.all(adsusers.map(e => getInfo(e))


```
the promise took 15 minutes to resolve.

**Comment by kritzware** [comment]
Hi @flasaracina, I'm still not able to recreate queries that take that long to resolve, even with your code and some large accounts that we have.

In general I wouldn't recommend a `Promise.all` with that many queries running concurrently though, it may improve your performance to lower that number i.e. run the customer queries in batches of 5 at a time.

Internally in the library, we're using [auto-generated gapic clients](https://github.com/googleapis/gapic-generator-typescript). I can see there is an [active high-priority issue](https://github.com/googleapis/gapic-generator-typescript/issues/823) regarding memory leaks and some connections not being closed, so perhaps that may help when it's resolved.

**Comment by kritzware** [comment]
I've taken a further look and there are some issues around the `GoogleAdsService` being very slow to initialise, as it requires all other protos within it. [See my reply here as well](https://github.com/Opteo/google-ads-api/issues/211#issuecomment-786600035).

We're also going to raise the issue with Google.

**Comment by kritzware** [comment]
This also only happens for the **first** API call per `Customer` instance as well. That may be useful if you're able to restructure your code somehow, but in your use case it looks like you need to do calls for many different customers.

**Comment by flasaracina** [comment]
@kritzware the code I am running is very similar to the barebone example I wrote here, so there isn't much to rewrite or to restructure, unfortunately. As you noticed, there are some serious problem related to the underneath google libraries.

For now I've decided to set aside gRPC for a while because I am on a deadline for this project, and now  I am building a tiny REST layer in order to fetch google ads data the "old way". So far the same call that took 42 seconds, got 60x time faster as it took only 0.7s 

I am interested in a solution though, so I'll stick around to see if Google will manage to solve this one

Thanks

**Comment by kritzware** [comment]
Glad to hear you have a temporary solution @flasaracina. 

You bring up the interesting point about the REST API being much quicker, and it's something we've thought about before. We've been quite _pro_ proto/gRPC as Google recommends it and claim that it's faster, but this hasn't been the case always, particularly with the new Gapic auto-generated clients.

 It could be interesting to think about using REST behind the scenes instead of gRPC in a future major version.

**Comment by kritzware** [comment]
This was their fix if you're interested: https://github.com/googleapis/gax-nodejs/pull/966

**Comment by rosslavery** [comment]
Curious about whether their fix will work for child processes spawned since I believe they operate in a totally different memory space than the parent process.

We use Bull (queue system) to run reports across a number of customers, and each job is spawned in a child process, and each responsible for a single report request. Concerned that each job will be affected by the 7 second startup time since each is effectively a "fresh" process. 🤔 

Thanks for the updates @kritzware

**Comment by flasaracina** [comment]
@kritzware that is indeed a good news! Thanks

**Comment by rosslavery** [comment]
> @rosslavery It's very likely that you'll continue to face the same slow startup issue on every new child process...
> 
> Can I ask how spawning a child process per job helps you in your project? Are you trying to better utilise a multi-core CPU?

I believe it helps Bull identify stalled jobs and also has the other benefit of any errors in the isolated job not affecting the main node process in the worker container. 

Concerning that each process might incur such a huge startup penalty...Yeesh.

> Sometimes jobs are more CPU intensive which will could lock the Node event loop for too long and Bull could decide the job has been stalled. To avoid this situation, it is possible to run the process functions in separate Node processes.

> We call this kind of processes for “sandboxed” processes, and they also have the property that if the crash they will not affect any other process, and a new process will be spawned automatically to replace it.
