### ISSUE TITLE
Question around querying nested attributes in campaign_criterion

### ISSUE THREAD

**Issue by kamrankhanwastaken** [Opteo/google-ads-api#235]
This can probably be tagged as a question, and I'm hoping it is useful for someone else too, but is there any particular reason why querying for nested attributes using the `report` function would throw an exception in the query below?
```
const locationCriteria = await customer.report(`SELECT
  campaign_criterion.campaign,
  campaign_criterion.location.geo_target_constant,
  campaign_criterion.proximity.geo_point.longitude_in_micro_degrees,
  campaign_criterion.proximity.geo_point.latitude_in_micro_degrees,
  campaign_criterion.proximity.radius,
  campaign_criterion.negative
FROM campaign_criterion
WHERE
  campaign_criterion.campaign = 'customers/{customer_id}/campaigns/{campaign_id}'
  AND campaign_criterion.type IN (LOCATION, PROXIMITY`)
```
I am using this from the [google ads api doc](https://developers.google.com/google-ads/api/docs/targeting/location-targeting#retrieve_geo_targets) but anything under `campaign_criterion.location` and `campaign_criterion.proximity` throws a `TypeError: Cannot read property 'nested attribute' of null` for every nested attribute.

Am I missing something here?

**Comment by kritzware** [comment]
This definitely seems like an issue we have in the parsing of the results. We'll look into it, thanks!

**Comment by WillCooter** [comment]
Unfortunately I haven't been able to replicate the issue you are experiencing, however I notice that you are using the `report` method with a GAQL query. The `report` method takes report options rather than a GAQL string, so you would be wanting to use the `query` method here. I also notice that the closing bracket after the second constraint in missing (there should be a closing bracket after `PROXIMITY`).

If you could amend these things and let me know if you are still having the same issues that would appreciated 🙂
