### ISSUE TITLE
Different return data structures for 'reportStream' and 'reportStreamRaw'

### ISSUE THREAD

**Issue by lushu** [Opteo/google-ads-api#254]
@WillCooter Thanks Will. I was testing on this new version and I would like to have your opinions on this issue: when I use `report` or `reportStream`, the result is clean and only contains fields that I put in the `ReportOptions`. However, if I use `reportStreamRaw`, the result contains a lot of fields that are not in `ReportOptions` with the NULL value. 

My questions are: 

1. I guess it was caused by the lower level lib `google-ads-node`. I knew there was a very big difference between the current `google-ads-node` and previous one. However, is this expected behaviour? 

2. How does current `google-ads-api` adapter to that? And is it possible to let `reportStreamRaw` behave in that way as well?

3. Will there be a big performance impact in this kind of transformation back and forth?

_Originally posted by @lushu in https://github.com/Opteo/google-ads-api/issues/237#issuecomment-821126695_

**Comment by WillCooter** [comment]
1. Yes, this is the expected behaviour. The raw result returned from Google Ads now contains many fields that were not requested with `null` values.
2. We handle this in `google-ads-api` by parsing the results of a query, which we do in the functions `query`, `report` and `reportStream`. Unfortunately this step is not possible for `reportStreamRaw` without intercepting the data events, which would defeat the purpose of the function (to return the raw stream as it comes from Google Ads). However, in the latest version we have also exposed the `parse` method from the api so that users can call it manually ([see here for an example](https://github.com/Opteo/google-ads-api#retrieve-keywords-with-a-raw-stream)).
3. Every effort has been made to keep the parsing function as performant as possible. However there are still considerations to be made by the user as to whether it is worth using for reports with many millions of rows.

**Comment by lushu** [comment]
Thank you @WillCooter for the quick answers. 

I have a follow-up: how the `reportStream` in the previous `google-ads-node` could just return the selected fields?

**Comment by WillCooter** [comment]
@lush Previously we had more control and were able to intercept each request and do parsing, even for streaming. However since upgrading `google-ads-node` to use v6.1 of the google ads api we are using mostly auto-generated code. The parsing is therefore now done in our `google-ads-api`, and we recommend any `google-ads-node` users to switch to `google-ads-api`.

**Comment by lushu** [comment]
Thanks @WillCooter . I have did something similar and the issue for big reports has been solved. Cheers.
