### ISSUE TITLE
Rate limit best practices / recommendations

### ISSUE THREAD

**Issue by rosslavery** [Opteo/google-ads-api#283]
I've read through the Ads API V7 migration notes about how Bottleneck was removed and left up to the developer to implement on their side.

Are there any recommendations or best practices you could provide on how you (Opteo) are implementing this on your side? I imagine using some of the new hooks features would help. Looking at the PR though, there was a significant amount of internal code that depended on Bottleneck, and I'm unsure on if we have the mechanisms needed to replicate all of that in application code only.

Once I have an understanding I'm happy to create a README PR.

**Comment by avermeil** [comment]
We spoke to our contacts at google about this, and they assured us that the rate limits are so high these days that it's extremely unlikely that we'll hit them. We removed all of our rate-limiting code in production, and we found that indeed, we didn't encounter the kinds of rate-limiting issues that we used to in the early days of the Google Ads API beta. We've been running like this ever since.

Note that there are two main levels of rate-limiting:
1. Developer token level (very high limit)
2. Customer level (less high limit)
(there are other service-level rate limits but they're internal to google and undocumented)

We sidestep the customer level rate limit by interleaving our api calls in our batch jobs (ie avoiding going over an entire customer at once).

That said, if your application is still hitting rate limits and you'd like to self-throttle, you could still do so by using the hooks, as you mentioned. 

Since the hooks are async, and are `awaited` internally before actually making any calls to google servers, you can use them to throttle your calls. Here's an (untested) example, where we `await` a dummy function on all of the relevant hooks. I've never tried using Bottleneck to wrap a dummy function like this, but I think it would work...

```javascript
    import Bottleneck from 'bottleneck'
    import { GoogleAdsApi } from 'google-ads-api'

    const client = new GoogleAdsApi({
        client_id: '<CLIENT-ID>',
        client_secret: '<CLIENT-SECRET>',
        developer_token: '<DEVELOPER-TOKEN>',
    })

    const throttler = new Bottleneck({/* Your throttling settings */})

    const onQueryStart = async () => {
        await throttler.wrap(async () => null)
    }
    const onStreamStart = async () => {
        await throttler.wrap(async () => null)
    }
    const onMutationStart = async () => {
        await throttler.wrap(async () => null)
    }

    const customer = client.Customer({
        // [...]
        hooks: { onQueryStart, onStreamStart, onMutationStart },
    })
```

If you do manage to get this working, a PR with an example would absolutely be awesome!

**Comment by rosslavery** [comment]
Thank you @avermeil for the explanation! I didn't realize the hooks are async and can therefore help control the throughput. 

I'm still waiting for a response from Google on our side re: an unusual uptick in `INTERNAL_ERROR` for our batch jobs since migrating to API V7. No application code has changed but the same jobs are failing much more than usual. My theory is they are rate limit errors not being returned properly.

As a related aside, I noticed the `logging` options were removed from the constructor, which makes it hard to provide Google support with raw request/response logs like before. I've been providing them `request_id` with the hope they can lookup the raw stuff on their side.

Once I get some clarity from Google on my errors I can put together a rate-limit solution and document it for the repo here too.
