### ISSUE TITLE
High RAM usage (130MB increase)

### ISSUE THREAD

**Issue by moshest** [Opteo/google-ads-api#290]
I notice that my service got a jump from ~65MB of RAM to ~190MB!

I debug the recent changes and I found that this related to `google-ads-api` library. Anyway we could reduce the RAM usage? 130MB just for this library is an overkill and I would have to find other alternatives..

**Comment by avermeil** [comment]
Hi @moshest -- You're right that this is a relatively "heavy" library.

Here are the points at which RAM is consumed:
- When the library is imported, to hold the base JS code (small amount of memory).
- When the first API call is made, we import all of the protos into the runtime nodejs process. Because there are so many protos in the Google Ads API, this will increase memory usage by a non-trivial amount, and won't be reclaimed until the process is killed. We're working on reducing this with our Google contacts, but it's challenging.
- When you make a API call (such as `report()` or `query()`, the data returned will increase your memory usage temporarily as we parse and hold onto the rows coming in. The amount of memory used is proportional to the amount of data downloaded. You can reduce this memory usage by using `reportStream()` to avoid holding onto the whole dataset at once.
