### ISSUE TITLE
Uncaught TypeError: customer.campaigns.list is not a function

### ISSUE THREAD

**Issue by almog-barel** [Opteo/google-ads-api#360]
using the example code 

```
(async()=>{
    const client = new GoogleAdsApi({
        client_id: googleClientId,
        client_secret: googleClientSecret,
        developer_token: adwordsDeveloperToken,
    })
        
    list = await client.listAccessibleCustomers(refreshToken)
    console.log(list);
    
    const customer = client.Customer({
        customer_account_id: list.resource_names[0],
        refresh_token: refreshToken,
    })

    customer.campaigns.list()
})()

```

i am getting a list from client.listAccessibleCustomers
but from client.listAccessibleCustomers

i am getting : TypeError: customer.campaigns.list is not a function

**Comment by kritzware** [comment]
Hi @almog-barel, the `list` functions are no longer supported in this API (for a few versions now). Our documentation at https://opteo.com/dev/google-ads-api is outdated and shouldn't be used, instead just refer to this repos README for now (new docs coming soon).

Instead of `list` you should use the `report` method and specify the exact fields you need.
