### ISSUE TITLE
Interacting with API package results in X is not a function

### ISSUE THREAD

**Issue by EngagementFactory** [Opteo/google-ads-api#375]
We are attempting to interact with the Google Ads API in order to create and update userlists (Audiences) that could then be used with campaigns etc.

We've worked through the steps provided by Google and it's documentations to create the Project and get an approved Developer Token. However when attempting to use the google-ads-api we consistently encounter errors such as: "TypeError: customer.campaigns.list is not a function" as an example.
Not sure if this helps but when logging out what exactly "customer.campaigns" is, it's a blank JSON object. I would have expected at least something here.

We've made use of the example codes found both here on Github, th NPM page itself as well as the documentations linked within. i.e. https://opteo.com/dev/google-ads-api
All without success. This is just using the basic example and of course filling in all our required informations.
```
import { GoogleAdsApi } from 'google-ads-api'

const client = new GoogleAdsApi({
    client_id: '<YOUR_CLIENT_ID>',
    client_secret: '<YOUR_CLIENT_SECRET>',
    developer_token: '<YOUR_DEVELOPER_TOKEN>',
})

const customer = client.Customer({
    customer_account_id: '123-123-123',
    login_customer_id: '456-456-456', // Optionally provide a login-customer-id
    linked_customer_id: '789-789-789', // Optionally provide a linked-customer-id
    refresh_token: '<YOUR_REFRESH_TOKEN>',
})

// If done correctly, you should now be able to list the campaigns in the account 123-123-123
customer.campaigns.list()
```
We have not declared a "linked_customer_id" but this is optional.
The get refresh token process has been followed as well and granted us a refresh token.

Currently we are unsure of precisely where we are going wrong. Are we missing something with this package specifically or perhaps this is related to something within the Google setup itself?
Any assistance here would be highly appreciated.

**Comment by WillCooter** [comment]
Hi @EngagementFactory, sorry that you've been confused here. Those docs were long out of date and have been very misleading. We have since taken them down as we have no plans to maintain them. The `.list()` method no longer exists on any entities, Google removed it from the API a few months ago. To get data you now need to do a [query](https://github.com/Opteo/google-ads-api#retrieve-campaigns-using-gaql) or [report](https://github.com/Opteo/google-ads-api#retrieve-campaigns-with-metrics), requesting the specific fields you are after.

I am surprised that logging `customer.campaigns` returned a blank JSON, the `campaigns` object should contain the mutation methods `create`, `update` and `remove`. Let me know how you get on with this information and if you need any more guidance.
