### ISSUE TITLE
can not find Opteo documentation for google-ads-api

### ISSUE THREAD

**Issue by kulubaev** [Opteo/google-ads-api#396]
can not find Opteo documentation for google-ads-api, 
where is it? was it offloaded?

**Comment by WillCooter** [comment]
Hi @kulubaev, the old documentation was over a year out of date as maintaining it had become to difficult. We had found that many of the issues posted here were happening because people were using the API based on those outdated docs. We now recommend using [the README of this library](https://github.com/Opteo/google-ads-api#readme) for functionality and [Google's own docs](https://developers.google.com/google-ads/api/reference/rpc/v11/overview) for ads reference.
