### ISSUE TITLE
How work with GenerateKeywordIdea geo_target_constants attributes

### ISSUE THREAD

**Issue by patrickpreston32** [Opteo/google-ads-api#406]
How can i pass geo_target_constants in keywordPlanIdeas
```
var generateKeywordIdeaResponse = await customer.keywordPlanIdeas.generateKeywordIdeas({
          customer_id: customer.credentials.customer_id,
          page_size: PAGE_SIZE,
          keyword_seed: keywordSeed,
          geo_target_constants: ["US"],
        //   historical_metrics_options: { include_average_cpc: true },
        }).catch((e) => console.error(e));
```

Getting this Error:  message: "Resource name 'US' is malformed: expected 'geoTargetConstants/{criterion_id}'."

**Comment by WillCooter** [comment]
A geo target constant is of the format expected in the error. For example, the location id for the US is `2840`, so instead of `"US"` you need to use `"geoTargetConstants/2840"`. All of Google's location ids can be found [here](https://developers.google.com/google-ads/api/reference/data/geotargets).
