### ISSUE TITLE
How to use a service account?

### ISSUE THREAD

**Issue by Madd0g** [Opteo/google-ads-api#44]
### I'm submitting a ...

-   [X] question about how to use this project

### Summary

Since I'm not going to be accessing other users' accounts from my server (only one predefined account), the google api console suggested I should use a service account to authenticate.

Is there a way to use the service account json file downloaded from the credential UI with this library? 

Thanks

**Comment by avermeil** [comment]
This library doesn't currently support service accounts, unfortunately, although it's something we could implement in the future.

Instead of a service account, is there a disadvantage to getting yourself a single refresh token that you can use forever? We have a tool to help you with this: https://refresh-token-helper.opteo.com/

**Comment by alessandro-aglietti** [comment]
@Madd0g you'll find a working solution here https://github.com/Opteo/google-ads-api/pull/199!
