### ISSUE TITLE
gRPC max message size (#43 continued..)

### ISSUE THREAD

**Issue by issacg** [Opteo/google-ads-api#46]
I can't seem to add comments to #43 - not sure if it's because of the way you guys set up workflow on issues or if something is b0rked on my end...  Would appreciate if someone could check into that and reply here, and otherwise try to resume the conversation for #43 on the thread for #43 :)

In any case, I wanted to say there that it happens for a query that is returning (or trying to return) 9MB of data 

For me it was enough to run a 30 day report on a busy account with lots of ads, and asking for lots of user-presentable strings, like the ad text, search keywords, search terms, and account/campaign/adgroup names (but YMMV based on your account activity.)

Regarding a solution, I'm far from a gRPC maven, but I've been seeing lots about a stream interface which allows a response (or request) to be split into several payloads...

Would this be relevant? https://grpc.github.io/grpc/node/grpc-ClientReadableStream.html

**Comment by kritzware** [comment]
Hmm, that's odd. I don't think we have any restrictions on commenting, so perhaps it's an issue on your end? No worries though, we can continue here.

Adding streamed responses is something we are considering for sure. It would be handled in our gRPC library [google-ads-node](https://github.com/opteo/google-ads-node) though, where I've opened an [issue](https://github.com/Opteo/google-ads-node/issues/14) on this topic. If this works out well, we would most likely implement streaming internally in this library for larger requests, so your code remains the same 👍

**Comment by avermeil** [comment]
@issacg, regarding the issues not working correctly: make sure you're not running adblock. The name of this repo causes issues with some github features sometimes.

If you're keen to get things working reliably on your end before @kritzware's solution, consider splitting up your request into two: the first with attributes, and the second with segments & metrics. Since you're segmenting by date 30x (I assume?), this will make your response sizes much smaller, since the attributes are wastefully repeated when you segment. You'll need to merge the results of the two request in your application code (on `resource_name`), but it sure beats downloading a 9MB payload!

**Comment by issacg** [comment]
Another option, for other stuck here, is to use the pagination controls available via `report`.  It's a bit of a hack, and a bad one too - since you'd need to guess around the payload size of a given page - but it works, and in theory is doing something similar to what streaming would be doing behind the scenes...

(it might be nice to offer `page_size` via `query`, too)

**Comment by avermeil** [comment]
It turns out that the limit of `4MB` was set client side by the [node-grpc](https://github.com/grpc/grpc-node) library that we use. We've [raised that limit](https://github.com/Opteo/google-ads-node/commit/baa8646496fa79e35d8f70892f9db851fe1b6e68) to `1GB` in our latest release, `2.1.1`. It's pretty likely that something else will break before you can actually download a 1GB report in a single query, but hey 🤷‍♂ 

Happy querying!
