### ISSUE TITLE
Members aren't being populated for Custom Interests 

### ISSUE THREAD

**Issue by Mattensor** [Opteo/google-ads-api#51]
Hey there 👋,

When I try to create a Custom Interest I get back an error which indicates members aren't being populated but I am passing through params which include a collection of CustomInterestMember objects.

I pass through the following params
```
{
  "type":3,
  "name":"I like dogs",
  "description":"We love dogs, dogs are the best",
  "members":[
    {"member_type":2,"parameter":"dog"}
  ]
}
```

I get back the following error:
```
code: { fieldError: 2 },
  request:
   { customerId: '4674531019',
     operationsList: [ [Object] ],
     validateOnly: false },
  request_id: 'BQbtQVg1e9ouMxsKPaea9g',
  location: 'operations[0].create.members[0]',
  failure:
   { Error: 3 INVALID_ARGUMENT: The required field was not present.
```

It appears that the member list (element 7) is an empty array - we'd expect it to have one element.
```
'7':
              [ { wrappers_: null,
                  messageId_: undefined,
                  arrayIndexOffset_: -1,
                  array: [],
                  pivot_: 1.7976931348623157e+308,
                  convertedFloatingPointFields_: {} } ] },
```

Is there anything that I am missing here?

**Comment by kritzware** [comment]
Hi @Mattensor , thanks for reporting this issue! We've identified the bug, which was happening over in [google-ads-node](https://github.com/opteo/google-ads-node). It's since been fixed, and your query should now work.

Make sure you upgrade to google-ads-api [`1.2.1`](https://www.npmjs.com/package/google-ads-api). Feel free to re-open this issue if the problem persists 👍
