### ISSUE TITLE
How to get campaign budget

### ISSUE THREAD

**Issue by AndriyGo** [Opteo/google-ads-api#62]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary

For each campaign in my account, I wish to extract `campaign_budget.amount_micros`. However, I cannot figure out a way to do this. If I list all my campaigns, I see that `campaign_budget` property is a URL. However, I am stuck at trying to figure out how I could query it.

Also, I will need to update it once I receive the value. I assume that I would struggle with it as well :)

**Comment by kritzware** [comment]
Hi @AndriyGo, 

In the Google Ads API, resources (such as a [Campaign](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.resources#campaign) or [Campaign Budget](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.resources#campaignbudget)) have a unique field, called the **resource name**. This looks like a URL, since the API is structured in that way. For campaign budgets, the resource URL uses this format: 
```
customers/{customer_id}/campaignBudgets/{budget_id}
```
The resource name is essentially a new unique way of identifying a resource in the Google Ads API, as opposed to ids, which the old AdWords API used.

There are a couple of different ways to retrieve the campaign budget for a specific campaign.

```javascript
// Get the campaign budget resource name
const [{ campaign_budget }] = await customer.campaigns.list({ limit: 1 })
const { resource_name } = campaign_budget

// Use the global report method to get the budget amount via the resource name
const budget = await customer.report({
    entity: 'campaign_budget',
    attributes: ['campaign_budget.amount_micros'],
    constraints: {
        'campaign_budget.resource_name': resource_name,
    },
})

console.log(budget)
/*
[ { campaign_budget:
     { resource_name: 'customers/123/campaignBudgets/321',
       amount_micros: 1000000 } } ]
*/
```

The method above uses two requests however. We can avoid this, by joining the campaign budgets whilst retrieving campaign data, using solely the `report` method:

```javascript
const campaigns = await gads.report({
    entity: 'campaign',
    // Notice here we specify "campaign" and "campaign_budget" fields
    attributes: ['campaign.name', 'campaign_budget.amount_micros'],
})

console.log(campaigns[0])
/*
[ { campaign:
    { resource_name: 'customers/123/campaigns/1',
        name: 'Campaign #1' },
    campaign_budget:
    { resource_name: 'customers/123/campaignBudgets/2',
        amount_micros: 1000000 } } ]
*/
```

For more details about which fields can be selected, [take a look at our documentation here!](https://opteo.com/dev/google-ads-api/#campaignbudget) More information on resource names and API structure, can be found [here in the official Google Ads API docs](https://developers.google.com/google-ads/api/docs/concepts/api-structure).

Let us know if this helpful or not, thanks! 👍
